### PR TITLE
Change shebang to /bin/bash since scripts use bashisms

### PR DESCRIPTION
**Pull request by khanku**
As reported in #32 shell scripts under nagios/bin/ make use of bashisms but are set to be executed by /bin/sh. This is problematic under Debian and derivatives which symlink /bin/sh to dash. For instance pmp-check-mysql-replication-delay does not run at all under Debian because of the "==" comparison on [line 74](https://github.com/percona/percona-monitoring-plugins/blob/d0eeb3696d812e5731430673ed749575358ece22/nagios/bin/pmp-check-mysql-replication-delay#L7).
This pull request changes the shebang of shell scripts under nagios/bin/ to /bin/bash since the scripts are effectively bash scripts.

### CODE REVIEW

**Comment by tersmitten** [comment]
What about `#!/usr/bin/env bash` (to make it more portable)?

**Comment by khanku** [comment]
Sounds reasonable.

**Comment by meineerde** [comment]
+1

**Comment by bliles** [comment]
This affects me too any chance of this getting merged soon?

**Pull request merged**
